METADATA: str = "metadata"
VIDEO: str = "vid"
FILE: str = "file"
RECORDED_START_DATE: str = "recorded_start_date"

DATE_FORMAT: str = "%Y-%m-%d %H:%M:%S.%f"
INPUT_FILE_PATH: str = "input_file_path"
DATA: str = "data"
DETECTIONS: str = "detections"
CLASS: str = "class"
CLASSIFIED: str = "classified"
FRAME: str = "frame"
OCCURRENCE: str = "occurrence"
LABEL: str = "label"
CONFIDENCE: str = "conf"
X: str = "x"
Y: str = "y"
W: str = "w"
H: str = "h"

TRACK_ID: str = "track-id"
