#!/bin/bash
CURRENT_DIR=`pwd`
MP4_FILENAME="Testvideo_Cars-Cyclist_FR20_2020-01-01_00-00-00.mp4"
OTDET_FILENAME="Testvideo_Cars-Cyclist_FR20_2020-01-01_00-00-00.otdet"
MP4_FILE="$CURRENT_DIR/tests/data/$MP4_FILENAME"
OTDET_FILE="$CURRENT_DIR/tests/data/$OTDET_FILENAME"
TMP_DEBUG_DIR="$CURRENT_DIR/.tmp/debug/"

mkdir -p $TMP_DEBUG_DIR
cp $MP4_FILE $TMP_DEBUG_DIR$MP4_FILENAME
cp $OTDET_FILE $TMP_DEBUG_DIR$OTDET_FILENAME
