"""Integration and unit tests for the BoT-SORT tracker adapter."""

from __future__ import annotations

import os
import shutil
from functools import cached_property
from pathlib import Path
from unittest.mock import Mock, patch

import numpy as np
import pytest

from OTVision import dataformat
from OTVision.application.config import (
    Config,
    TrackConfig,
    _TrackBotSortConfig,
    _TrackIouConfig,
)
from OTVision.application.track.tracking_run_id import StrIdGenerator
from OTVision.config import CONFIG
from OTVision.domain.detection import Detection
from OTVision.domain.frame import DetectedFrame
from OTVision.track.tracker.tracker_plugin_botsort import (
    _extract_frame_rate_from_metadata,
)
from tests.conftest import YieldFixture
from tests.track.helper.data_builder import create_frame

pytest.importorskip("ultralytics")

from OTVision import version  # noqa: E402
from OTVision.track.builder import TrackBuilder  # noqa: E402
from OTVision.track.tracker.tracker_plugin_botsort import BotsortTracker  # noqa: E402

version.otvision_version = Mock(return_value="ignored")
version.ottrack_version = Mock(return_value="ignored")
version.otdet_version = Mock(return_value="ignored")

TEST_RUN_ID = "test-botsort-run"


class MockBotsortTrackBuilder(TrackBuilder):
    @cached_property
    def tracking_run_id_generator(self) -> StrIdGenerator:
        return lambda: TEST_RUN_ID


def _create_botsort_track_config(
    paths: list,
    t_min: int = 5,
    t_miss_max: int = 51,
    overwrite: bool = True,
) -> TrackConfig:
    return TrackConfig(
        paths=paths,
        run_chained=True,
        tracker_type="botsort",
        botsort=_TrackBotSortConfig(
            t_min=t_min,
            t_miss_max=t_miss_max,
            tracker_params={
                "gmc_method": "none",
                "track_high_thresh": 0.25,
                "track_low_thresh": 0.1,
                "new_track_thresh": 0.25,
                "with_reid": False,
            },
        ),
        overwrite=overwrite,
    )


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def test_track_dir(test_data_dir: Path) -> Path:
    return test_data_dir / "track"


@pytest.fixture
def test_track_tmp_dir(
    test_data_tmp_dir: Path, test_track_dir: Path
) -> YieldFixture[Path]:
    test_track_tmp_dir = test_data_tmp_dir / "track_botsort"
    test_track_tmp_dir.mkdir(exist_ok=True)
    shutil.copytree(test_track_dir, test_track_tmp_dir, dirs_exist_ok=True)
    # Remove existing .ottrk so we can regenerate them
    extension = CONFIG["DEFAULT_FILETYPE"]["TRACK"]
    for f in test_track_tmp_dir.rglob(f"*{extension}"):
        f.unlink()
    yield test_track_tmp_dir
    shutil.rmtree(test_track_tmp_dir)


# ---------------------------------------------------------------------------
# Test 1: End-to-end BoT-SORT tracking produces .ottrk output
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_botsort_tracking_produces_ottrk_output(
    test_track_tmp_dir: Path,
) -> None:
    """Run BoT-SORT on real .otdet test data and verify .ottrk files appear."""
    input_folder = test_track_tmp_dir / "default"
    track_config = _create_botsort_track_config(
        paths=[str(input_folder.relative_to(os.getcwd()))],
    )
    builder = MockBotsortTrackBuilder()
    builder.update_current_track_config.update(track_config)
    otvision_track = builder.build()

    await otvision_track.start()

    extension = CONFIG["DEFAULT_FILETYPE"]["TRACK"]
    output_files = list(input_folder.glob(f"*{extension}"))
    assert len(output_files) > 0, "No .ottrk files generated by BoT-SORT"


# ---------------------------------------------------------------------------
# Test 2: Multi-video group reset
# ---------------------------------------------------------------------------


def _make_detection(x: float = 100.0, y: float = 100.0) -> Detection:
    return Detection(label="car", conf=0.9, x=x, y=y, w=50.0, h=30.0)


def _make_frame(
    frame_no: int,
    source: str = "video1.otdet",
    detections: list[Detection] | None = None,
) -> DetectedFrame:
    if detections is None:
        detections = [_make_detection()]
    return create_frame(
        frame_number=frame_no,
        detections=detections,
        input_file_path=Path(source),
    )


def _mock_get_current_config(track_config: TrackConfig) -> Mock:
    config = Config(track=track_config)
    mock = Mock()
    mock.get.return_value = config
    return mock


_FPS_METADATA = {dataformat.VIDEO: {dataformat.ACTUAL_FPS: 20.0}}


@patch(
    "OTVision.track.tracker.tracker_plugin_botsort.read_json_bz2_metadata",
    return_value=_FPS_METADATA,
)
def test_botsort_resets_state_on_new_video_group(
    _mock_metadata: Mock,
) -> None:
    """Feeding frame.no=0 a second time must clear all state from the first group."""
    track_config = _create_botsort_track_config(paths=[], t_miss_max=100)
    tracker = BotsortTracker(get_current_config=_mock_get_current_config(track_config))

    id_gen = iter(range(1, 10000))

    # --- Video group 1 ---
    group1_ids: set[int] = set()
    for i in range(5):
        result = tracker.track_frame(_make_frame(frame_no=i, source="v1.otdet"), id_gen)
        for det in result.detections:
            group1_ids.add(det.track_id)

    assert len(group1_ids) > 0, "No tracks assigned in group 1"

    # --- Video group 2 (frame.no resets to 0) ---
    group2_ids: set[int] = set()
    for i in range(5):
        result = tracker.track_frame(_make_frame(frame_no=i, source="v2.otdet"), id_gen)
        for det in result.detections:
            group2_ids.add(det.track_id)

    assert len(group2_ids) > 0, "No tracks assigned in group 2"
    assert group1_ids.isdisjoint(group2_ids), (
        f"Track IDs leaked across video groups: {group1_ids & group2_ids}"
    )


# ---------------------------------------------------------------------------
# Test 3: FPS extraction error paths
# ---------------------------------------------------------------------------


def test_fps_extraction_non_otdet_source_raises() -> None:
    """Non-.otdet source file must raise ValueError."""
    track_config = _create_botsort_track_config(paths=[])
    tracker = BotsortTracker(get_current_config=_mock_get_current_config(track_config))
    frame = _make_frame(frame_no=0, source="video.mp4")

    with pytest.raises(ValueError, match="requires FPS metadata from an .otdet"):
        tracker.track_frame(frame, iter(range(1, 100)))


@patch(
    "OTVision.track.tracker.tracker_plugin_botsort.read_json_bz2_metadata",
    side_effect=OSError("unreadable"),
)
def test_fps_extraction_unreadable_file_raises(_mock: Mock) -> None:
    """Unreadable .otdet file must raise ValueError."""
    track_config = _create_botsort_track_config(paths=[])
    tracker = BotsortTracker(get_current_config=_mock_get_current_config(track_config))
    frame = _make_frame(frame_no=0, source="video.otdet")

    with pytest.raises(ValueError, match="readable .otdet metadata"):
        tracker.track_frame(frame, iter(range(1, 100)))


@patch(
    "OTVision.track.tracker.tracker_plugin_botsort.read_json_bz2_metadata",
    return_value={},
)
def test_fps_extraction_missing_fps_keys_raises(_mock: Mock) -> None:
    """Missing FPS keys in metadata must raise ValueError."""
    track_config = _create_botsort_track_config(paths=[])
    tracker = BotsortTracker(get_current_config=_mock_get_current_config(track_config))
    frame = _make_frame(frame_no=0, source="video.otdet")

    with pytest.raises(ValueError, match="requires FPS metadata in .otdet"):
        tracker.track_frame(frame, iter(range(1, 100)))


def test_extract_frame_rate_returns_none_for_missing_video_section() -> None:
    assert _extract_frame_rate_from_metadata({}) is None


def test_extract_frame_rate_returns_none_for_zero_fps() -> None:
    metadata = {dataformat.VIDEO: {dataformat.ACTUAL_FPS: 0, dataformat.RECORDED_FPS: 0}}
    assert _extract_frame_rate_from_metadata(metadata) is None
