---
# This workflow will install Python dependencies, run tests

name: Run CI/CD

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install test dependencies
        run: |
          pip install pytest
          pip install pytest-cov
          pip install flake8
          pip install mypy
          pip install deepdiff
          pip install jsonschema
          python -c 'from OTVision.helpers.machine \
          import print_has_cuda; print_has_cuda()'
      - name: Lint codebase
        run: |
          flake8 .
      - name: Execute static type checking
        run: |
          mypy .
      - name: Test with pytest
        run: pytest --cov=OTVision tests/
