---
name: Remove Issue from Projects

on:
  issues:
    types: [unlabeled]

jobs:
  remove-from-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Remove bugs and features from ToDo-List
        uses: alex-page/github-project-automation-plus@v0.8.1
        if: |
          !contains(github.event.issue.labels.*.name, 'bug') &&
          !contains(github.event.issue.labels.*.name, 'feature')
        with:
          project: ToDo OpenTrafficCam
          column: To do
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
          action: delete

      - name: Remove questions from Weekly-Discussion
        uses: alex-page/github-project-automation-plus@v0.8.1
        if: |
          !contains(github.event.issue.labels.*.name, 'question')
        with:
          project: OTC Core Developer Weekly Meeting
          column: questions
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
          action: delete

      - name: Remove public bugs from Weekly-Discussion
        uses: alex-page/github-project-automation-plus@v0.8.1
        if: |
          !contains(github.event.issue.labels.*.name, 'bug')
        with:
          project: OTC Core Developer Weekly Meeting
          column: public bugs
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
          action: delete

      # Move to other column if label is present
      - name: Move questions to Weekly-Discussion
        uses: alex-page/github-project-automation-plus@v0.8.1
        if: |
          contains(github.event.issue.labels.*.name, 'question')
        with:
          project: OTC Core Developer Weekly Meeting
          column: questions
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}

      - name: Move public bugs to Weekly-Discussion
        uses: alex-page/github-project-automation-plus@v0.8.1
        if: |
          contains(github.event.issue.labels.*.name, 'bug')
        with:
          project: OTC Core Developer Weekly Meeting
          column: public bugs
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
