name: Remove Issue from Project

on:
  issues:
    types: [unlabeled]

jobs:
  ToDo-List:
    runs-on: ubuntu-latest
    steps:
      - name: Remove former bugs and features from ToDo-List
        uses: alex-page/github-project-automation-plus@v0.5.1
        if: |
          !contains(github.event.issue.labels.*.name, 'bug') &&
          !contains(github.event.issue.labels.*.name, 'feature')
        with:
          project: ToDo-List
          column: To do
          repo-token: ${{ secrets.TOKEN_SEBASTIAN }}
          action: delete
  Wish-List:
    runs-on: ubuntu-latest
    steps:
      - name: Remove former ideas from Wish-List
        uses: alex-page/github-project-automation-plus@v0.5.1
        if: |
          !contains(github.event.issue.labels.*.name, 'idea')
        with:
          project: Wish-List
          column: ${{ github.event.repository.name }}
          repo-token: ${{ secrets.TOKEN_SEBASTIAN }}
          action: delete
  Discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Remove former questions from Friday-Discussion
        uses: alex-page/github-project-automation-plus@v0.5.1
        if: |
          !contains(github.event.issue.labels.*.name, 'question')
        with:
          project: OTC Core Developer Friday-Meeting
          column: neu
          repo-token: ${{ secrets.TOKEN_SEBASTIAN }}
          action: delete
