name: PR to Project

on:
  pull_request:
    types: [opened, reopened]

jobs:
  ToDo-List:
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to ToDo-List
        uses: alex-page/github-project-automation-plus@v0.5.1
        with:
          project: ToDo-List
          column: In progress
          repo-token: ${{ secrets.TOKEN_SEBASTIAN }}
